version: '1'
services:
  gastos:
    container_name: teste-back
    image:  teste-back:latest  
    ports:
      - '8080:8080'
    links:
      - mongo
    volumes:
      - /application/application.properties
  mongo:
    container_name: mongoDB
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
